# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_Test
  pod 'Alamofire'
  pod 'AAExtensions', '0.1.4'
  pod 'IQKeyboardManagerSwift'
end
